name: SurvivalCore
version: '${project.version}'
main: one.nxeu.survivalcore.SurvivalCore
api-version: 1.19

commands:
  message:
    description: "message"
    usage: "/message <get> [key]"
  vl:
    description: "svc"
    usage: "/svc <get> <mspt|tps>"
